# build the docker image
# push the docker image to docker hub
# ssh into VM and start the new image
name: deploy backend

on:
    push:
        branches:
            - main

jobs:
    # defining the automations scipt and config for the build part
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                  context: . #build from the root folder
                  file: ./docker/dockerfile.backend
                  push: true
                  tags: siddhantbh/week27-2-be:${{github.sha}}

            - name: Deploy to VM via SSH
              uses: appleboy/ssh-action@v0.1.10
              with: 
                host: ${{secrets.VM_IP}}
                username: ${{ secrets.VM_USER }}
                key: ${{ secrets.VM_PRIVATE_KEY }}
                script: |
                  cd /deploy
                  docker compose pull
                  docker compose up -d


